import type { Metadata } from "next";
import { Container } from "@/components/ui/container";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms and conditions for using the Al-Wahab Solar Traders website and services.",
};

export default function TermsPage() {
  return (
    <div className="pt-32 pb-24 sm:pt-40">
      <Container>
        <div className="mx-auto max-w-[760px]">
          <div className="glass rounded-2xl p-8 sm:p-10">
            <p className="text-[13px] text-slate-500">Last updated: 29 July 2026</p>

            <h1 className="font-display mt-4 text-[32px] font-semibold text-white">
              Terms of Service
            </h1>

            <div className="mt-8 space-y-8 text-[15px] leading-relaxed text-slate-400">
              <section>
                <h2 className="font-display text-lg font-semibold text-white">
                  1. The estimate
                </h2>
                <p className="mt-3">
                  Estimates generated by this tool are indicative and based on current Lahore
                  market rates at the time of generation. They are valid for 14 days from
                  issue. Final pricing, specifications, project phases and tasks are confirmed
                  by our engineer after a free site survey.
                </p>
              </section>

              <section>
                <h2 className="font-display text-lg font-semibold text-white">
                  2. Free to use
                </h2>
                <p className="mt-3">
                  Using the estimator, creating an account, saving estimates and booking a
                  site survey are free and carry no obligation. You are not charged unless you
                  accept a quotation and sign an agreement to proceed.
                </p>
              </section>

              <section>
                <h2 className="font-display text-lg font-semibold text-white">
                  3. Accuracy
                </h2>
                <p className="mt-3">
                  We make every effort to keep rates current and calculations correct.
                  However, market prices fluctuate and site conditions vary. The estimate is a
                  guide, not a binding offer. The binding offer is the quotation issued after
                  the site survey.
                </p>
              </section>

              <section>
                <h2 className="font-display text-lg font-semibold text-white">
                  4. Your account
                </h2>
                <p className="mt-3">
                  You are responsible for keeping your login credentials secure. If you
                  suspect unauthorised access, contact us immediately. You may delete your
                  account at any time from your profile settings.
                </p>
              </section>

              <section>
                <h2 className="font-display text-lg font-semibold text-white">
                  5. Intellectual property
                </h2>
                <p className="mt-3">
                  The design, code, content and branding of this website are owned by
                  Al-Wahab Solar Traders. You may not reproduce, distribute or reverse-engineer
                  any part without written permission.
                </p>
              </section>

              <section>
                <h2 className="font-display text-lg font-semibold text-white">
                  6. Limitation of liability
                </h2>
                <p className="mt-3">
                  Al-Wahab Solar Traders is not liable for decisions made based on indicative
                  estimates. Our liability in connection with any project is limited to the
                  contract value of that project.
                </p>
              </section>

              <section>
                <h2 className="font-display text-lg font-semibold text-white">
                  7. Governing law
                </h2>
                <p className="mt-3">
                  These terms are governed by the laws of Pakistan. Any disputes will be
                  resolved in the courts of Lahore.
                </p>
              </section>
            </div>
          </div>
        </div>
      </Container>
    </div>
  );
}
